language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=03f2c0f86171b6f77d98548c0dd09735c0e816bed1350187625e357923f7c703

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 

script:
  - make lint
  - make test

  notifications:
  - email: false