language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=7958a867a0aeb81df7e71ee2dcd3e34b572509fd5a3aa83958938b7acd8498b1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 

script:
  - make lint
  - make test

  notifications:
  - email: false